import { Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis, CartesianGrid, Legend } from 'recharts'
import { apiGet } from '../api/client'
import { useFetchOnMount } from '../hooks/useApi'
import type { BenchmarkResponse } from '../types/api'
import { Card, ErrorBanner, PageHeader, Spinner, Table } from '../components/ui'

export default function ClassicalBenchmarkPage() {
  const benchmark = useFetchOnMount(() => apiGet<BenchmarkResponse>('/classical/benchmark'), [])

  return (
    <div className="mx-auto max-w-4xl">
      <PageHeader
        title="Classical Benchmark"
        description="Measured (not asserted) scaling of classical factoring attacks against real RSA keypairs at increasing bit sizes -- generated by scripts/benchmark_classical.py and loaded here, not regenerated on page view."
      />

      {benchmark.status === 'loading' && <Spinner label="Loading benchmark data…" />}
      {benchmark.status === 'error' && (
        <ErrorBanner message={`${benchmark.message} — run "python scripts/benchmark_classical.py" to generate it.`} />
      )}

      {benchmark.status === 'success' && (
        <>
          <Card>
            <div className="h-80 w-full">
              <ResponsiveContainer>
                <LineChart data={benchmark.data.rows} margin={{ left: 8, right: 16, top: 8, bottom: 8 }}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#1b2430" />
                  <XAxis
                    dataKey="bits"
                    stroke="#8c919b"
                    tick={{ fill: '#8c919b', fontSize: 12 }}
                    label={{ value: 'RSA modulus size (bits)', position: 'insideBottom', offset: -6, fill: '#8c919b', fontSize: 12 }}
                  />
                  <YAxis
                    scale="log"
                    domain={['auto', 'auto']}
                    stroke="#8c919b"
                    tick={{ fill: '#8c919b', fontSize: 12 }}
                    label={{ value: 'time (s, log scale)', angle: -90, position: 'insideLeft', fill: '#8c919b', fontSize: 12 }}
                  />
                  <Tooltip
                    contentStyle={{ background: '#0b1018', border: '1px solid #1b2430', borderRadius: 2, fontSize: 12 }}
                    labelStyle={{ color: '#eee8da' }}
                  />
                  <Legend wrapperStyle={{ fontSize: 12, color: '#8c919b' }} iconType="plainline" />
                  <Line
                    type="monotone"
                    dataKey="trial_division_seconds"
                    name="trial division"
                    stroke="#c99545"
                    strokeWidth={2.5}
                    dot={{ r: 3.5, strokeWidth: 0 }}
                    activeDot={{ r: 5 }}
                  />
                  <Line
                    type="monotone"
                    dataKey="pollards_rho_seconds"
                    name="Pollard's rho"
                    stroke="#8065b8"
                    strokeWidth={2.5}
                    dot={{ r: 3.5, strokeWidth: 0 }}
                    activeDot={{ r: 5 }}
                  />
                </LineChart>
              </ResponsiveContainer>
            </div>
            <p className="mt-3 text-sm text-ink-muted">
              Trial division's time grows unmistakably exponentially with key size; Pollard's rho
              fares somewhat better (roughly O(n^1/4) vs. O(n^1/2)) but still can't touch real
              key sizes -- a real RSA-2048 modulus is ~34x more bits than the largest point
              plotted here.
            </p>
          </Card>

          <Card className="mt-6">
            <h2 className="mb-3 font-medium text-ink">Raw data ({benchmark.data.source_file})</h2>
            <Table>
              <thead>
                <tr className="border-b border-line text-xs tracking-wide text-ink-muted uppercase">
                  <th className="px-3 py-2">Bits</th>
                  <th className="px-3 py-2">n</th>
                  <th className="px-3 py-2">Trial division (s)</th>
                  <th className="px-3 py-2">Pollard's rho (s)</th>
                </tr>
              </thead>
              <tbody>
                {benchmark.data.rows.map((row) => (
                  <tr key={row.bits} className="border-b border-line/60 last:border-0">
                    <td className="px-3 py-2 text-ink">{row.bits}</td>
                    <td className="px-3 py-2 font-mono text-xs text-ink-muted">{row.n}</td>
                    <td className="px-3 py-2 font-mono text-xs text-ink-muted">{row.trial_division_seconds.toFixed(4)}</td>
                    <td className="px-3 py-2 font-mono text-xs text-ink-muted">{row.pollards_rho_seconds.toFixed(4)}</td>
                  </tr>
                ))}
              </tbody>
            </Table>
          </Card>
        </>
      )}
    </div>
  )
}
